file:
  upload:
    save: file/upload

server:
  error:
    whitelabel:
      enabled: false

  servlet:
    encoding:
      force-response: true

spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:./test  #접속 URL
    username: test
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug